version: "3.8"

services:
  hubspot-app:
    build: .
    container_name: hubspot-iwh-i-practicum
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
